spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.206.78:3306/drug?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Root123..
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /drug
